user_pref("browser.cache.disk.capacity", 0);
user_pref("browser.download.useDownloadDir", false);
user_pref("browser.newtab.url", "about:blank");
user_pref("browser.privatebrowsing.autostart", true);
user_pref("browser.startup.homepage", "about:blank");
user_pref("general.autoscroll", true);
user_pref("general.smoothscroll", false);
user_pref("pdfjs.disabled", true);
user_pref("signon.rememberSignons", false);
